# Generated by Django 4.1.7 on 2023-03-25 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewAirports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_airport_class',
            name='GROWTH_RATE',
        ),
    ]
