# Generated by Django 4.1.7 on 2023-03-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewAirports', '0002_remove_new_airport_class_growth_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_airport_class',
            name='SHORTENED_NAME',
            field=models.CharField(default='', max_length=15),
        ),
    ]
