# Generated by Django 4.1.7 on 2023-03-15 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CITY_CLASS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=30)),
                ('AIRPORT_NAME', models.CharField(max_length=3)),
                ('GROWTH_RATE', models.DecimalField(decimal_places=2, max_digits=6)),
                ('IMG', models.ImageField(blank=True, upload_to='')),
                ('FORECASTED_DEMAND', models.IntegerField()),
                ('TOURISM_GROWTH', models.IntegerField()),
                ('ECONOMIC_GROWTH', models.IntegerField()),
                ('EDUCATION_GROWTH', models.IntegerField()),
                ('POPULATION_GROWTH', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GENERAL_PARAMS_CLASS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FORECAST_YEAR', models.IntegerField(default=2033)),
                ('PRESENT_YEAR', models.IntegerField(default=2023)),
                ('CAPACITY_NARROWBODY', models.IntegerField(default=300)),
                ('CAPACITY_TURBOPROP', models.IntegerField(default=100)),
                ('FLEET_NARROWBODY', models.IntegerField(default=5)),
                ('FLEET_TURBOPROP', models.IntegerField(default=5)),
                ('INFLATION_RATE', models.DecimalField(decimal_places=2, default=7.0, max_digits=5)),
                ('FIXED_COST', models.IntegerField()),
                ('OPERATING_COST', models.IntegerField()),
                ('OTHER_COST', models.IntegerField()),
                ('MIN_PROFIT_MARGIN', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ANALYSIS_POINTS', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ROUTE_CLASS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DURATION', models.IntegerField()),
                ('DISTANCE', models.IntegerField()),
                ('GROWTH_IN', models.DecimalField(decimal_places=2, max_digits=6)),
                ('GROWTH_OUT', models.DecimalField(decimal_places=2, max_digits=6)),
                ('PRICE_IN_MARKET', models.IntegerField()),
                ('PRICE_OUT_MARKET', models.IntegerField()),
                ('NUM_IN_MARKET', models.IntegerField()),
                ('NUM_OUT_MARKET', models.IntegerField()),
                ('MARKET_SHARE_IN', models.DecimalField(decimal_places=2, max_digits=5)),
                ('MARKET_SHARE_OUT', models.DecimalField(decimal_places=2, max_digits=5)),
                ('FROM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city', to='RouteDev.city_class')),
                ('TO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_city', to='RouteDev.city_class')),
            ],
        ),
        migrations.CreateModel(
            name='ROUTE_PARAMS_CLASS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRICE_IN', models.IntegerField()),
                ('PRICE_OUT', models.IntegerField()),
                ('ROUTE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RouteDev.route_class')),
            ],
        ),
        migrations.CreateModel(
            name='OPTION_CLASS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FEASIBILITY', models.BooleanField(default=False)),
                ('NUM_PLANES', models.CharField(max_length=200)),
                ('PROFIT_MARGIN', models.DecimalField(decimal_places=2, max_digits=6)),
                ('PROFITABILITY_YEAR', models.IntegerField()),
                ('OCCUPANCY_RATE', models.DecimalField(decimal_places=2, max_digits=5)),
                ('RANK', models.IntegerField(default=-1)),
                ('ROUTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteDev.route_class')),
            ],
        ),
    ]
