# Generated by Django 4.1.7 on 2023-03-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_params_class',
            name='SAMPLE_NAME',
            field=models.CharField(default='Sample 1', max_length=20),
            preserve_default=False,
        ),
    ]
