# Generated by Django 4.1.7 on 2023-03-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDev', '0002_general_params_class_sample_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRPORT_CLASS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=30)),
                ('AIRPORT_NAME', models.CharField(max_length=3)),
                ('IS_HUB', models.BooleanField(default=False)),
            ],
        ),
    ]
