# Generated by Django 4.1.7 on 2023-03-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDev', '0004_airport_class_latitude_airport_class_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONNECTION_CLASS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NODES', models.ManyToManyField(to='RouteDev.airport_class')),
            ],
        ),
    ]
