# Generated by Django 4.1.7 on 2023-03-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDev', '0006_remove_connection_class_nodes_connection_class_node1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_class',
            name='SELECTED',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route_class',
            name='SELECTED',
            field=models.BooleanField(default=False),
        ),
    ]
