# Generated by Django 4.1.7 on 2023-03-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDev', '0007_city_class_selected_route_class_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection_class',
            name='TWO_WAY_FLIGHT',
            field=models.BooleanField(default=False),
        ),
    ]
