# Generated by Django 4.1.7 on 2023-03-18 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDev', '0009_rename_duration_route_class_duration_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route_class',
            name='FROM',
        ),
        migrations.RemoveField(
            model_name='route_class',
            name='TO',
        ),
        migrations.AddField(
            model_name='route_class',
            name='AIRPORT',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_city', to='RouteDev.airport_class'),
        ),
        migrations.AddField(
            model_name='route_class',
            name='CITY',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_city', to='RouteDev.city_class'),
        ),
    ]
