# Generated by Django 4.1.7 on 2023-03-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDev', '0010_remove_route_class_from_remove_route_class_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route_class',
            name='PRICE_IN_MARKET',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='route_class',
            name='PRICE_OUT_MARKET',
            field=models.CharField(max_length=10),
        ),
    ]
