# Generated by Django 4.1.7 on 2023-03-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDev', '0011_alter_route_class_price_in_market_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport_class',
            name='LATITUDE',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airport_class',
            name='LONGITUDE',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='city_class',
            name='GROWTH_RATE',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='city_class',
            name='LATITUDE',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='city_class',
            name='LONGITUDE',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='general_params_class',
            name='INFLATION_RATE',
            field=models.FloatField(default=7.0),
        ),
        migrations.AlterField(
            model_name='general_params_class',
            name='MIN_PROFIT_MARGIN',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='option_class',
            name='OCCUPANCY_RATE',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='option_class',
            name='PROFIT_MARGIN',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='route_class',
            name='GROWTH',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='route_class',
            name='GROWTH_IN',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='route_class',
            name='GROWTH_OUT',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='route_class',
            name='MARKET_SHARE_IN',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='route_class',
            name='MARKET_SHARE_OUT',
            field=models.FloatField(default=-1),
        ),
    ]
