# Generated by Django 4.1.7 on 2023-03-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDev', '0012_alter_airport_class_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option_class',
            name='CAPACITY',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option_class',
            name='DEMAND',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option_class',
            name='EARNINGS',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option_class',
            name='EXPENSES',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
