# Generated by Django 4.1.7 on 2023-03-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDev', '0013_option_class_capacity_option_class_demand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option_class',
            name='PROFITABILITY_YEAR',
            field=models.CharField(max_length=5),
        ),
    ]
