# Generated by Django 4.1.7 on 2023-03-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDev', '0015_remove_city_class_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_class',
            name='INFO',
            field=models.CharField(default='', max_length=100),
        ),
    ]
