# Generated by Django 4.1.7 on 2023-03-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDev', '0016_city_class_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='route_class',
            name='RAILWAYS_CAPACITY',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='route_class',
            name='RAILWAYS_DURATION',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='route_class',
            name='RAILWAYS_NUM',
            field=models.IntegerField(default=0),
        ),
    ]
