# Generated by Django 4.1.7 on 2023-03-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDev', '0017_route_class_railways_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route_class',
            name='DURATION',
            field=models.IntegerField(default=0),
        ),
    ]
