# Generated by Django 4.1.7 on 2023-03-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDev', '0019_general_params_class_demand_fulfilment_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_params_class',
            name='ONLY_HUBS',
            field=models.CharField(default='ONLY TO HUBS', max_length=20),
        ),
    ]
