# Generated by Django 4.1.7 on 2023-03-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDev', '0021_alter_general_params_class_only_hubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_params_class',
            name='ONLY_HUBS',
            field=models.BooleanField(default=True),
        ),
    ]
