# Generated by Django 4.1.7 on 2023-03-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteDev', '0022_alter_general_params_class_only_hubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport_class',
            name='SHORTENED_NAME',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='city_class',
            name='SHORTENED_NAME',
            field=models.CharField(default='', max_length=15),
        ),
    ]
